[project]
name = "doc-parser-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "av",
    "easyocr",
    "fastapi",
    "filetype",
    "pydantic-settings",
    "langchain",
    "langchain-community",
    "langchain-core",
    "langchain-groq",
    "opencv-python-headless",
    "pandas",
    "pillow",
    "pymupdf",
    "python-docx",
    "python-dotenv",
    "python-multipart",
    "sentencepiece",
    "torch",
    "transformers",
    "uvicorn",
    "faiss-cpu",
    "sentence-transformers",
    "langchain-huggingface",
    "openpyxl",
    "streamlit>=1.55.0",
]
